   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.30  10/19/06            */
   /*                                                     */
   /*                 AGENDA HEADER FILE                  */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*   Provides functionality for examining, manipulating,     */
/*   adding, and removing activations from the agenda.       */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Removed CONFLICT_RESOLUTION_STRATEGIES and     */
/*            DYNAMIC_SALIENCE compilation flags.            */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*            Added EnvGetActivationBasisPPForm function.    */
/*                                                           */
/*      6.30: Added salience groups to improve performance   */
/*            with large numbers of activations of different */
/*            saliences.                                     */
/*                                                           */
/*************************************************************/

#ifndef _H_agenda

#define _H_agenda

#ifndef _H_ruledef
#include "ruledef.h"
#endif
#ifndef _H_symbol
#include "symbol.h"
#endif
#ifndef _H_match
#include "match.h"
#endif

#define WHEN_DEFINED 0
#define WHEN_ACTIVATED 1
#define EVERY_CYCLE 2

#define MAX_DEFRULE_SALIENCE  10000
#define MIN_DEFRULE_SALIENCE -10000
  
/*******************/
/* DATA STRUCTURES */
/*******************/

struct activation
  {
   struct defrule *theRule;
   struct partialMatch *basis;
   int salience;
   unsigned long long timetag;
   int randomID;
   struct activation *prev;
   struct activation *next;
  };

struct salienceGroup
  {
   int salience;
   struct activation *first;
   struct activation *last;
   struct salienceGroup *next;
   struct salienceGroup *prev;
  };

typedef struct activation ACTIVATION;

#define AGENDA_DATA 17

struct agendaData
  { 
#if DEBUGGING_FUNCTIONS
   unsigned WatchActivations;
#endif
   unsigned long NumberOfActivations;
   unsigned long long CurrentTimetag;
   int AgendaChanged;
   intBool SalienceEvaluation;
   int Strategy;
  };

#define EnvGetActivationSalience(theEnv,execStatus,actPtr) (((struct activation *) actPtr)->salience)
#define GetActivationRule(actPtr) (((struct activation *) actPtr)->theRule)
#define GetActivationBasis(actPtr) (((struct activation *) actPtr)->basis)
#define AgendaData(theEnv,execStatus) ((struct agendaData *) GetEnvironmentData(theEnv,execStatus,AGENDA_DATA))

#ifdef LOCALE
#undef LOCALE
#endif

#ifdef _AGENDA_SOURCE_
#define LOCALE
#else
#define LOCALE extern
#endif

/****************************************/
/* GLOBAL EXTERNAL FUNCTION DEFINITIONS */
/****************************************/

#define Agenda(a,b) EnvAgenda(GetCurrentEnvironment(),getCurrentExecutionState(),a,b)
#define DeleteActivation(a) EnvDeleteActivation(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define GetActivationName(a) EnvGetActivationName(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define GetActivationPPForm(a,b,c) EnvGetActivationPPForm(GetCurrentEnvironment(),getCurrentExecutionState(),a,b,c)
#define GetActivationSalience(actPtr) (((struct activation *) actPtr)->salience)
#define GetAgendaChanged() EnvGetAgendaChanged(GetCurrentEnvironment(),getCurrentExecutionState())
#define GetNextActivation(a) EnvGetNextActivation(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define GetSalienceEvaluation() EnvGetSalienceEvaluation(GetCurrentEnvironment(),getCurrentExecutionState())
#define Refresh(a) EnvRefresh(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define RefreshAgenda(a) EnvRefreshAgenda(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define ReorderAgenda(a) EnvReorderAgenda(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define SetActivationSalience(a,b) EnvSetActivationSalience(GetCurrentEnvironment(),getCurrentExecutionState(),a,b)
#define SetAgendaChanged(a) EnvSetAgendaChanged(GetCurrentEnvironment(),getCurrentExecutionState(),a)
#define SetSalienceEvaluation(a) EnvSetSalienceEvaluation(GetCurrentEnvironment(),getCurrentExecutionState(),a)

   LOCALE void                    AddActivation               (void *,EXEC_STATUS,void *,void *);
   LOCALE void                    ClearRuleFromAgenda         (void *,EXEC_STATUS,void *);
   LOCALE void                   *EnvGetNextActivation        (void *,EXEC_STATUS,void *);
   LOCALE char                   *EnvGetActivationName        (void *,EXEC_STATUS,void *);
   LOCALE int                     EnvSetActivationSalience    (void *,EXEC_STATUS,void *,int);
   LOCALE void                    EnvGetActivationPPForm      (void *,EXEC_STATUS,char *,unsigned,void *);
   LOCALE void                    EnvGetActivationBasisPPForm (void *,EXEC_STATUS,char *,unsigned,void *);
   LOCALE intBool                 MoveActivationToTop         (void *,EXEC_STATUS,void *);
   LOCALE intBool                 EnvDeleteActivation         (void *,EXEC_STATUS,void *);
   LOCALE intBool                 DetachActivation            (void *,EXEC_STATUS,void *);
   LOCALE void                    EnvAgenda                   (void *,EXEC_STATUS,char *,void *);
   LOCALE void                    RemoveActivation            (void *,EXEC_STATUS,void *,int,int);
   LOCALE void                    RemoveAllActivations        (void *,EXEC_STATUS);
   LOCALE int                     EnvGetAgendaChanged         (void *,EXEC_STATUS);
   LOCALE void                    EnvSetAgendaChanged         (void *,EXEC_STATUS,int);
   LOCALE unsigned long           GetNumberOfActivations      (void *,EXEC_STATUS);
   LOCALE intBool                 EnvGetSalienceEvaluation    (void *,EXEC_STATUS);
   LOCALE intBool                 EnvSetSalienceEvaluation    (void *,EXEC_STATUS,intBool);
   LOCALE void                    EnvRefreshAgenda            (void *,EXEC_STATUS,void *);
   LOCALE void                    EnvReorderAgenda            (void *,EXEC_STATUS,void *);
   LOCALE void                    InitializeAgenda            (void *,EXEC_STATUS);
   LOCALE void                   *SetSalienceEvaluationCommand(void *,EXEC_STATUS);
   LOCALE void                   *GetSalienceEvaluationCommand(void *,EXEC_STATUS);
   LOCALE void                    RefreshAgendaCommand        (void *,EXEC_STATUS);
   LOCALE void                    RefreshCommand              (void *,EXEC_STATUS);
   LOCALE intBool                 EnvRefresh                  (void *,EXEC_STATUS,void *);
#if DEBUGGING_FUNCTIONS
   LOCALE void                    AgendaCommand               (void *,EXEC_STATUS);
#endif

#endif

