   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.24  06/05/06            */
   /*                                                     */
   /*          MISCELLANEOUS FUNCTIONS HEADER FILE        */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*************************************************************/

#ifndef _H_miscfun

#define _H_miscfun

#ifdef LOCALE
#undef LOCALE
#endif

#ifdef _MISCFUN_SOURCE_
#define LOCALE
#else
#define LOCALE extern
#endif

   LOCALE void                           MiscFunctionDefinitions(void *,EXEC_STATUS);
   LOCALE void                           CreateFunction(void *,EXEC_STATUS,DATA_OBJECT_PTR);
   LOCALE long long                      SetgenFunction(void *,EXEC_STATUS);
   LOCALE void                          *GensymFunction(void *,EXEC_STATUS);
   LOCALE void                          *GensymStarFunction(void *,EXEC_STATUS);
   LOCALE long long                      RandomFunction(void *,EXEC_STATUS);
   LOCALE void                           SeedFunction(void *,EXEC_STATUS);
   LOCALE long long                      LengthFunction(void *,EXEC_STATUS);
   LOCALE void                           ConserveMemCommand(void *,EXEC_STATUS);
   LOCALE long long                      ReleaseMemCommand(void *,EXEC_STATUS);
   LOCALE long long                      MemUsedCommand(void *,EXEC_STATUS);
   LOCALE long long                      MemRequestsCommand(void *,EXEC_STATUS);
   LOCALE void                           OptionsCommand(void *,EXEC_STATUS);
   LOCALE void                          *OperatingSystemFunction(void *,EXEC_STATUS);
   LOCALE void                           ExpandFuncCall(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE void                           DummyExpandFuncMultifield(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE void                          *CauseEvaluationError(void *,EXEC_STATUS);
   LOCALE intBool                        SetSORCommand(void *,EXEC_STATUS);
   LOCALE void                          *GetFunctionRestrictions(void *,EXEC_STATUS);
   LOCALE void                           AproposCommand(void *,EXEC_STATUS);
   LOCALE void                          *GensymStar(void *,EXEC_STATUS);
   LOCALE void                           GetFunctionListFunction(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE void                           FuncallFunction(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE void                           NewFunction(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE void                           CallFunction(void *,EXEC_STATUS,DATA_OBJECT *);
   LOCALE double                         TimerFunction(void *,EXEC_STATUS);
   LOCALE double                         TimeFunction(void *,EXEC_STATUS);

#endif






