   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.24  06/05/06            */
   /*                                                     */
   /*          DEFTEMPLATE BASIC COMMANDS MODULE          */
   /*******************************************************/

/*************************************************************/
/* Purpose: Implements core commands for the deftemplate     */
/*   construct such as clear, reset, save, undeftemplate,    */
/*   ppdeftemplate, list-deftemplates, and                   */
/*   get-deftemplate-list.                                   */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable log to logName        */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*            Corrected code to remove compiler warnings     */
/*            when ENVIRONMENT_API_ONLY flag is set.         */
/*                                                           */
/*************************************************************/

#define _TMPLTBSC_SOURCE_

#include "setup.h"

#if DEFTEMPLATE_CONSTRUCT

#include <stdio.h>
#define _STDIO_INCLUDED_
#include <string.h>

#include "argacces.h"
#include "memalloc.h"
#include "scanner.h"
#include "router.h"
#include "extnfunc.h"
#include "constrct.h"
#include "cstrccom.h"
#include "factrhs.h"
#include "cstrcpsr.h"
#include "tmpltpsr.h"
#include "tmpltdef.h"
#if BLOAD || BLOAD_ONLY || BLOAD_AND_BSAVE
#include "tmpltbin.h"
#endif
#if CONSTRUCT_COMPILER && (! RUN_TIME)
#include "tmpltcmp.h"
#endif
#include "tmpltutl.h"
#include "envrnmnt.h"

#include "tmpltbsc.h"

/***************************************/
/* LOCAL INTERNAL FUNCTION DEFINITIONS */
/***************************************/

#if ! DEFFACTS_CONSTRUCT
   static void                    ResetDeftemplates(void *,EXEC_STATUS);
#endif
   static void                    ClearDeftemplates(void *,EXEC_STATUS);
   static void                    SaveDeftemplates(void *,EXEC_STATUS,void *,char *);

/*********************************************************************/
/* DeftemplateBasicCommands: Initializes basic deftemplate commands. */
/*********************************************************************/
globle void DeftemplateBasicCommands(
  void *theEnv,
  EXEC_STATUS)
  {
#if ! DEFFACTS_CONSTRUCT
   EnvAddResetFunction(theEnv,execStatus,"deftemplate",ResetDeftemplates,0);
#endif
   EnvAddClearFunction(theEnv,execStatus,"deftemplate",ClearDeftemplates,0);
   AddSaveFunction(theEnv,execStatus,"deftemplate",SaveDeftemplates,10);

#if ! RUN_TIME
   EnvDefineFunction2(theEnv,execStatus,"get-deftemplate-list",'m',PTIEF GetDeftemplateListFunction,"GetDeftemplateListFunction","01w");
   EnvDefineFunction2(theEnv,execStatus,"undeftemplate",'v',PTIEF UndeftemplateCommand,"UndeftemplateCommand","11w");
   EnvDefineFunction2(theEnv,execStatus,"deftemplate-module",'w',PTIEF DeftemplateModuleFunction,"DeftemplateModuleFunction","11w");

#if DEBUGGING_FUNCTIONS
   EnvDefineFunction2(theEnv,execStatus,"list-deftemplates",'v', PTIEF ListDeftemplatesCommand,"ListDeftemplatesCommand","01w");
   EnvDefineFunction2(theEnv,execStatus,"ppdeftemplate",'v',PTIEF PPDeftemplateCommand,"PPDeftemplateCommand","11w");
#endif

#if (BLOAD || BLOAD_ONLY || BLOAD_AND_BSAVE)
   DeftemplateBinarySetup(theEnv,execStatus);
#endif

#if CONSTRUCT_COMPILER && (! RUN_TIME)
   DeftemplateCompilerSetup(theEnv,execStatus);
#endif

#endif
  }

/*************************************************************/
/* ResetDeftemplates: Deftemplate reset routine for use with */
/*   the reset command. Asserts the initial-fact fact when   */
/*   the deffacts construct has been disabled.               */
/*************************************************************/
#if ! DEFFACTS_CONSTRUCT
static void ResetDeftemplates(
  void *theEnv,
  EXEC_STATUS)
  {
   struct fact *factPtr;

   factPtr = StringToFact(theEnv,execStatus,"(initial-fact)");

   if (factPtr == NULL) return;

   EnvAssert(theEnv,execStatus,(void *) factPtr, FALSE);
 }
#endif

/*****************************************************************/
/* ClearDeftemplates: Deftemplate clear routine for use with the */
/*   clear command. Creates the initial-facts deftemplate.       */
/*****************************************************************/
static void ClearDeftemplates(
  void *theEnv,
  EXEC_STATUS)
  {
#if (! RUN_TIME) && (! BLOAD_ONLY)

   CreateImpliedDeftemplate(theEnv,execStatus,(SYMBOL_HN *) EnvAddSymbol(theEnv,execStatus,"initial-fact"),FALSE);
#else
#if MAC_MCW || WIN_MCW || MAC_XCD
#pragma unused(theEnv,execStatus)
#endif
#endif
  }

/**********************************************/
/* SaveDeftemplates: Deftemplate save routine */
/*   for use with the save command.           */
/**********************************************/
static void SaveDeftemplates(
  void *theEnv,
  EXEC_STATUS,
  void *theModule,
  char *logicalName)
  {   
   SaveConstruct(theEnv,execStatus,theModule,logicalName,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct);
  }

/**********************************************/
/* UndeftemplateCommand: H/L access routine   */
/*   for the undeftemplate command.           */
/**********************************************/
globle void UndeftemplateCommand(
  void *theEnv,
  EXEC_STATUS)
  {   
   UndefconstructCommand(theEnv,execStatus,"undeftemplate",DeftemplateData(theEnv,execStatus)->DeftemplateConstruct); 
  }

/**************************************/
/* EnvUndeftemplate: C access routine */
/*   for the undeftemplate command.   */
/**************************************/
globle intBool EnvUndeftemplate(
  void *theEnv,
  EXEC_STATUS,
  void *theDeftemplate)
  {   
   return(Undefconstruct(theEnv,execStatus,theDeftemplate,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct)); 
  }

/****************************************************/
/* GetDeftemplateListFunction: H/L access routine   */
/*   for the get-deftemplate-list function.         */
/****************************************************/
globle void GetDeftemplateListFunction(
  void *theEnv,
  EXEC_STATUS,
  DATA_OBJECT_PTR returnValue)
  {   
   GetConstructListFunction(theEnv,execStatus,"get-deftemplate-list",returnValue,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct); 
  }

/***********************************************/
/* EnvGetDeftemplateList: C access routine for */
/*   the get-deftemplate-list function.        */
/***********************************************/
globle void EnvGetDeftemplateList(
  void *theEnv,
  EXEC_STATUS,
  DATA_OBJECT_PTR returnValue,
  void *theModule)
  {   
   GetConstructList(theEnv,execStatus,returnValue,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct,(struct defmodule *) theModule); 
  }

/***************************************************/
/* DeftemplateModuleFunction: H/L access routine   */
/*   for the deftemplate-module function.          */
/***************************************************/
globle void *DeftemplateModuleFunction(
  void *theEnv,
  EXEC_STATUS)
  {   
   return(GetConstructModuleCommand(theEnv,execStatus,"deftemplate-module",DeftemplateData(theEnv,execStatus)->DeftemplateConstruct)); 
  }

#if DEBUGGING_FUNCTIONS

/**********************************************/
/* PPDeftemplateCommand: H/L access routine   */
/*   for the ppdeftemplate command.           */
/**********************************************/
globle void PPDeftemplateCommand(
  void *theEnv,
  EXEC_STATUS)
  {   
   PPConstructCommand(theEnv,execStatus,"ppdeftemplate",DeftemplateData(theEnv,execStatus)->DeftemplateConstruct); 
  }

/***************************************/
/* PPDeftemplate: C access routine for */
/*   the ppdeftemplate command.        */
/***************************************/
globle int PPDeftemplate(
  void *theEnv,
  EXEC_STATUS,
  char *deftemplateName,
  char *logicalName)
  {   
   return(PPConstruct(theEnv,execStatus,deftemplateName,logicalName,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct)); 
  }

/*************************************************/
/* ListDeftemplatesCommand: H/L access routine   */
/*   for the list-deftemplates command.          */
/*************************************************/
globle void ListDeftemplatesCommand(
  void *theEnv,
  EXEC_STATUS)
  {    
   ListConstructCommand(theEnv,execStatus,"list-deftemplates",DeftemplateData(theEnv,execStatus)->DeftemplateConstruct); 
  }

/*****************************************/
/* EnvListDeftemplates: C access routine */
/*   for the list-deftemplates command.  */
/*****************************************/
globle void EnvListDeftemplates(
  void *theEnv,
  EXEC_STATUS,
  char *logicalName,
  void *theModule)
  {   
   ListConstruct(theEnv,execStatus,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct,logicalName,(struct defmodule *) theModule); 
  }

/***********************************************************/
/* EnvGetDeftemplateWatch: C access routine for retrieving */
/*   the current watch value of a deftemplate.             */
/***********************************************************/
#if WIN_BTC
#pragma argsused
#endif
globle unsigned EnvGetDeftemplateWatch(
  void *theEnv,
  EXEC_STATUS,
  void *theTemplate)
  { 
#if MAC_MCW || WIN_MCW || MAC_XCD
#pragma unused(theEnv,execStatus)
#endif

   return(((struct deftemplate *) theTemplate)->watch); 
  }

/*********************************************************/
/* EnvSetDeftemplateWatch:  C access routine for setting */
/*   the current watch value of a deftemplate.           */
/*********************************************************/
#if WIN_BTC
#pragma argsused
#endif
globle void EnvSetDeftemplateWatch(
  void *theEnv,
  EXEC_STATUS,
  unsigned newState,
  void *theTemplate)
  {
#if MAC_MCW || WIN_MCW || MAC_XCD
#pragma unused(theEnv,execStatus)
#endif

   ((struct deftemplate *) theTemplate)->watch = newState; 
  }

/**********************************************************/
/* DeftemplateWatchAccess: Access routine for setting the */
/*   watch flag of a deftemplate via the watch command.   */
/**********************************************************/
#if WIN_BTC
#pragma argsused
#endif
globle unsigned DeftemplateWatchAccess(
  void *theEnv,
  EXEC_STATUS,
  int code,
  unsigned newState,
  EXPRESSION *argExprs)
  {
#if MAC_MCW || WIN_MCW || MAC_XCD
#pragma unused(code)
#endif

   return(ConstructSetWatchAccess(theEnv,execStatus,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct,newState,argExprs,
                                  EnvGetDeftemplateWatch,EnvSetDeftemplateWatch));
  }

/*************************************************************************/
/* DeftemplateWatchPrint: Access routine for printing which deftemplates */
/*   have their watch flag set via the list-watch-items command.         */
/*************************************************************************/
#if WIN_BTC
#pragma argsused
#endif
globle unsigned DeftemplateWatchPrint(
  void *theEnv,
  EXEC_STATUS,
  char *logName,
  int code,
  EXPRESSION *argExprs)
  {
#if MAC_MCW || WIN_MCW || MAC_XCD
#pragma unused(code)
#endif

   return(ConstructPrintWatchAccess(theEnv,execStatus,DeftemplateData(theEnv,execStatus)->DeftemplateConstruct,logName,argExprs,
                                    EnvGetDeftemplateWatch,EnvSetDeftemplateWatch));
  }

#endif /* DEBUGGING_FUNCTIONS */

#endif /* DEFTEMPLATE_CONSTRUCT */


