(set-strategy depth)
(unwatch all)
; bigbug4.bat test
(open "Results//bigbug.rsl" bigbug "w")
(dribble-on "Actual//bigbug.out")
(clear)
(progn (release-mem) TRUE)
(mem-used)
(load-facts bigbug.fct)
(clear)
(progn (release-mem) TRUE)
(mem-used)
(load bigbug.clp)
(reset)
(clear)
(progn (release-mem) TRUE)
(mem-used)
(dribble-off)
(load "compline.clp")
(printout bigbug "bigbug.bat differences are as follows:" crlf)
(compare-files "Expected//bigbug.out" "Actual//bigbug.out" bigbug)
; close result file
(close bigbug)
