(batch "dftmpcmd.tst")
(clear)
(batch "dfgblcmd.tst")
(clear)
(batch "memrycmd.tst")
(clear)
(batch "miscfnx.tst")
(clear)
(batch "dfrulcmd.tst")
(clear)
(batch "seqop.tst")
(clear)
(batch "tceplace.tst")
