(unwatch all)
(clear)
(dribble-on "Actual//ceerr.out")
(load "ceerr.clp")
(dribble-off)
(clear)
(open "Results//ceerr.rsl" ceerr "w")
(load "compline.clp")
(printout ceerr "ceerr.clp differences are as follows:" crlf)
(compare-files "Expected//ceerr.out" "Actual//ceerr.out" ceerr)
(close ceerr)
