(unwatch all)
(clear)
(setgen 1)
(load class.clp)
(dribble-on "Actual//class.out")
(batch "class.bat")
(dribble-off)
(clear)
(open "Results//class.rsl" class "w")
(load "compline.clp")
(printout class "class.clp differences are as follows:" crlf)
(compare-files "Expected//class.out" "Actual//class.out" class)
(close class)
