(unwatch all)
(clear)
(load "coolfnx.clp")
(dribble-on "Actual//coolfnx.out")
(batch "coolfnx.bat")
(dribble-off)
(clear)
(open "Results//coolfnx.rsl" coolfnx "w")
(load "compline.clp")
(printout coolfnx "coolfnx.bat differences are as follows:" crlf)
(compare-files "Expected//coolfnx.out" "Actual//coolfnx.out" coolfnx)
(close coolfnx)
