(unwatch all)
(clear)
(dribble-on "Actual//dfgblcmd.out")
(batch "dfgblcmd.bat")
(dribble-off)
(clear)
(open "Results//dfgblcmd.rsl" dfgblcmd "w")
(load "compline.clp")
(printout dfgblcmd "dfgblcmd.bat differences are as follows:" crlf)
(compare-files "Expected//dfgblcmd.out" "Actual//dfgblcmd.out" dfgblcmd)
(close dfgblcmd)
