(deffunction bogus (?a ?b $?c)
   (printout t "Random action" crlf))
(deffunction bogus2 ())
(ppdeffunction bogus)
(ppdeffunction bad)
(ppdeffunction 1)
(ppdeffunction)
(list-deffunctions)
(undeffunction bogus)
(list-deffunctions)
(undeffunction bad)
(undeffunction 1)
(undeffunction)
(undeffunction *)
(list-deffunctions)
