(unwatch all)
(clear)
(set-strategy depth)
(open "Results//drtest07.rsl" drtest07 "w")
(dribble-on "Actual//drtest07.out")
(batch "drtest07.bat")
(dribble-off)
(load "compline.clp")
(printout drtest07 "drtest07.bat differences are as follows:" crlf)
(compare-files "Expected//drtest07.out" "Actual//drtest07.out" drtest07)
; close result file
(close drtest07)
