(load "dyobjcst.clp")
(describe-class BASE)
(describe-class DERIVE-1-1)
(describe-class DERIVE-1-2)
(reset)
(defglobal ?*iaddress* = (instance-address [base]))
(send [base] put-symbol 34)
(send [base] put-fact-address ?*iaddress*)
(set-dynamic-constraint-checking FALSE)
(send [base] put-fact-address ?*iaddress*)
(set-dynamic-constraint-checking TRUE)
(send [base] put-instance-address ?*iaddress*)
(send [base] put-external-address ?*iaddress*)
(send [base] put-address ?*iaddress*)
(send [derive-1-1] put-address)
(send [derive-1-1] put-address ?*iaddress*)
(send [derive-1-1] put-address ?*iaddress* ?*iaddress*)
(send [derive-1-1] put-address ?*iaddress* ?*iaddress* ?*iaddress*)
(send [derive-1-1] put-address ?*iaddress* ?*iaddress* ?*iaddress* ?*iaddress*)
(send [derive-1-1] put-any 45)
(send [derive-1-1] put-any 123 123)
(send [derive-1-1] put-any 7.34)
(send [derive-1-1] put-any def)
(send [derive-1-1] put-any "abc")
(send [derive-1-1] put-any "def")
(send [derive-1-1] put-any 5.0)
(send [derive-1-1] put-any 123)
