(unwatch all)
(clear)
(dribble-on "Actual//factsfun.out")
(batch "factsfun.bat")
(dribble-off)
(clear)
(open "Results//factsfun.rsl" factsfun "w")
(load "compline.clp")
(printout factsfun "factsfun.bat differences are as follows:" crlf)
(compare-files "Expected//factsfun.out" "Actual//factsfun.out" factsfun)
(close factsfun)
