(unwatch all)
(clear)
(dribble-on "Actual//factscmd.out")
(batch "factscmd.bat")
(dribble-off)
(clear)
(open "Results//factscmd.rsl" factscmd "w")
(load "compline.clp")
(printout factscmd "factscmd.bat differences are as follows:" crlf)
(compare-files "Expected//factscmd.out" "Actual//factscmd.out" factscmd)
(close factscmd)
