(unwatch all)
(clear)
(dribble-on "Actual//fctpcstr.out")
(load "fctpcstr.clp")
(rules)
(dribble-off)
(clear)
(open "Results//fctpcstr.rsl" fctpcstr "w")
(load "compline.clp")
(printout fctpcstr "fctpcstr.clp differences are as follows:" crlf)
(compare-files "Expected//fctpcstr.out" "Actual//fctpcstr.out" fctpcstr)
(close fctpcstr)
