(unwatch all)
(clear)
(dribble-on "Actual//focusexe.out")
(batch "focusexe.bat")
(dribble-off)
(clear)
(open "Results//focusexe.rsl" focusexe "w")
(load "compline.clp")
(printout focusexe "focusexe.bat differences are as follows:" crlf)
(compare-files "Expected//focusexe.out" "Actual//focusexe.out" focusexe)
(close focusexe)
