(unwatch all)
(clear)
(load "gnrcprc.clp")
(dribble-on "Actual//gnrcprc.out")
(testit)
(dribble-off)
(clear)
(open "Results//gnrcprc.rsl" gnrcprc "w")
(load "compline.clp")
(printout gnrcprc "gnrcprc.clp differences are as follows:" crlf)
(compare-files "Expected//gnrcprc.out" "Actual//gnrcprc.out" gnrcprc)
(close gnrcprc)
