(unwatch all)
(clear)
(conserve-mem off)
(dribble-on "Actual//gnrccmd.out")
(batch "gnrccmd.bat")
(dribble-off)
(clear)
(open "Results//gnrccmd.rsl" gnrccmd "w")
(load "compline.clp")
(printout gnrccmd "gnrccmd.clp differences are as follows:" crlf)
(compare-files "Expected//gnrccmd.out" "Actual//gnrccmd.out" gnrccmd)
(close gnrccmd)
