(unwatch all)
(clear)
(progn
  (bind ?old (set-sequence-operator-recognition TRUE))
  (load "gnrcovl.clp")
  (set-sequence-operator-recognition ?old))
(dribble-on "Actual//gnrcovl.out")
(testit)
(dribble-off)
(clear)
(open "Results//gnrcovl.rsl" gnrcovl "w")
(load "compline.clp")
(printout gnrcovl "gnrcovl.clp differences are as follows:" crlf)
(compare-files "Expected//gnrcovl.out" "Actual//gnrcovl.out" gnrcovl)
(close gnrcovl)
