(unwatch all)
(clear)
(dribble-on "Actual//inserr.out")
(batch "inserr.bat")
(dribble-off)
(clear)
(open "Results//inserr.rsl" inserr "w")
(load "compline.clp")
(printout inserr "inserr.bat differences are as follows:" crlf)
(compare-files "Expected//inserr.out" "Actual//inserr.out" inserr)
(close inserr)
