(unwatch all)
(clear)
(dribble-on "Actual//memrycmd.out")
(batch "memrycmd.bat")
(dribble-off)
(clear)
(open "Results//memrycmd.rsl" memrycmd "w")
(load "compline.clp")
(printout memrycmd "memrycmd.bat differences are as follows:" crlf)
(compare-files "Expected//memrycmd.out" "Actual//memrycmd.out" memrycmd)
(close memrycmd)
