(unwatch all)
(clear)
(dribble-on "Actual//modulcmd.out")
(batch "modulcmd.bat")
(dribble-off)
(clear)
(open "Results//modulcmd.rsl" modulcmd "w")
(load "compline.clp")
(printout modulcmd "modulcmd.bat differences are as follows:" crlf)
(compare-files "Expected//modulcmd.out" "Actual//modulcmd.out" modulcmd)
(close modulcmd)
