(load "stobjcst.clp")
(list-defrules)
(describe-class BASE)
(describe-class DERIVE1)
(describe-class DERIVE2)
(describe-class DERIVE3)
(clear)
(defclass A (is-a USER)
  (slot foo (cardinality 3 4)))
(defclass A (is-a USER)
  (slot foo (type SYMBOL) (range 3 4)))
(defclass A (is-a USER)
  (slot foo (min-number-of-elements 3)))
(defclass A (is-a USER)
  (slot foo (allowed-words abc)))
(defclass A (is-a USER)
  (slot foo (allowed-values)))
(defclass A (is-a USER)
  (slot foo (allowed-integers abc)))
(defclass A (is-a USER)
   (slot foo (type INTEGER) (default abc)))
(defclass A (is-a USER)
   (slot foo (type INTEGER) (default-dynamic abc)))
(set-static-constraint-checking FALSE)
(defclass A (is-a USER)
   (slot foo (type INTEGER) (default abc)))
(defclass B (is-a USER)
   (slot foo (type INTEGER) (default-dynamic abc)))
(set-static-constraint-checking TRUE)
(clear)
