(unwatch all)
(clear)
(dribble-on "Actual//textpro.out")
(batch "textpro.bat")
(dribble-off)
(clear)
(open "Results//textpro.rsl" textpro "w")
(load "compline.clp")
(printout textpro "textpro.bat differences are as follows:" crlf)
(compare-files "Expected//textpro.out" "Actual//textpro.out" textpro)
(close textpro)
