(fetch "textpro.dat")
(print-region t "textpro.dat" root)
(print-region t "textpro.dat" ^ root1 sub)
(print-region t "textpro.dat" sub)
(print-region t "textpro.dat")
(print-region t "textpro.dat" subtopic2)
(print-region t "textpro.dat" ^ root2)
(print-region t "textpro.dat" ^ r s)
(print-region 1 2 3)
(print-region t 2 3)
(defglobal ?*cnt* = 0)
(while (< ?*cnt* 100) do
  (print-region t "textpro.dat" junk)
  (bind ?*cnt* (+ ?*cnt* 1)))
(toss "textpro.dat")
(toss "textpro.dat")
(fetch "textpro.doc")
(fetch "textpro.dat")
(get-region "textpro.dat" root)
(get-region "textpro.dat" ^ root1 sub)
(get-region "textpro.dat" sub)
(get-region "textpro.dat")
(get-region "textpro.dat" subtopic2)
(get-region "textpro.dat" ^ root2)
(get-region "textpro.dat" ^ r s)
(get-region 2 3)
(bind ?*cnt* 0)
(while (< ?*cnt* 100) do
  (get-region "textpro.dat" junk)
  (bind ?*cnt* (+ ?*cnt* 1)))
(toss "textpro.dat")
