(unwatch all)
(clear)
(dribble-on "Actual//tmpldflt.out")
(batch "tmpldflt.bat")
(dribble-off)
(clear)
(open "Results//tmpldflt.rsl" tmpldflt "w")
(load "compline.clp")
(printout tmpldflt "tmpldflt.bat differences are as follows:" crlf)
(compare-files "Expected//tmpldflt.out" "Actual//tmpldflt.out" tmpldflt)
(close tmpldflt)
