(unwatch all)
(clear)
(dribble-on "Actual//visible.out")
(load "visible.clp")
(go)
(dribble-off)
(clear)
(open "Results//visible.rsl" visible "w")
(load "compline.clp")
(printout visible "visible.clp differences are as follows:" crlf)
(compare-files "Expected//visible.out" "Actual//visible.out" visible)
(close visible)
