(unwatch all)
(clear)
(dribble-on "Actual//classerr.out")
(batch "classerr.bat")
(dribble-off)
(clear)
(open "Results//classerr.rsl" classerr "w")
(load "compline.clp")
(printout classerr "classerr.bat differences are as follows:" crlf)
(compare-files "Expected//classerr.out" "Actual//classerr.out" classerr)
(close classerr)
