(describe-class OBJECT)
(describe-class USER)
(describe-class PRIMITIVE)
(describe-class MULTIFIELD)
(describe-class NUMBER)
(describe-class EXTERNAL-ADDRESS)
(describe-class LEXEME)
(describe-class INTEGER)
(describe-class FLOAT)
(describe-class SYMBOL)
(describe-class STRING)
(list-defclasses)
(describe-class A1)
(describe-class B1)
(make-instance a21 of A2)
(make-instance a22 of A2)
(send [a21] print)
(send [a22] print)
(make-instance a3 of A3)
(nth 2 (send [a3] get-foo))
(send [a3] put-bar 45)
(send [a3] get-bar)
(make-instance a4 of A4)
(send [a4] print)
(send [a4] put-foo 56)
(send [a4] put-bar 104)
(make-instance [b4] of A4)
(send [b4] print)
(send [b4] put-foo 34)
(send [b4] put-woz 68)
(send [a4] print)
(send [b4] print)
(describe-class A5)
(make-instance a6 of A6 (bar 34))
(make-instance a6 of A6 (foo 34) (woz 65))
(send [a6] put-bar 1)
(send [a6] put-woz 1)
(send [a6] print)
(describe-class A7)
(describe-class B7)
(describe-class C8)
(describe-class B9)
(make-instance a9 of A9)
(make-instance b9 of B9)
(send [a9] get-foo)
(send [b9] get-foo)
(make-instance global-test of GLOBAL-TEST)
(send [global-test] print)
(bind ?*global-test* 200)
(initialize-instance global-test)
(send [global-test] print)
