(unwatch all)
(clear)
(load "cnstrsn.clp")
(dribble-on "Actual//cnstrsn.out")
(batch "cnstrsn.bat")
(dribble-off)
(clear)
(open "Results//cnstrsn.rsl" cnstrsn "w")
(load "compline.clp")
(printout cnstrsn "cnstrsn.clp differences are as follows:" crlf)
(compare-files "Expected//cnstrsn.out" "Actual//cnstrsn.out" cnstrsn)
(close cnstrsn)
