(list-defrules)
(get-defrule-list)
(list-deffacts)
(get-deffacts-list)
(list-deftemplates)
(get-deftemplate-list)
(list-defglobals)
(get-defglobal-list)
(list-deffunctions)
(get-deffunction-list)
(list-defgenerics)
(get-defgeneric-list)
(list-defmethods)
(get-defmethod-list)
(list-defmethods (nth 1 (get-defmethod-list)))
(get-defmethod-list (nth 1 (get-defmethod-list)))
(get-method-restrictions oof 50)
(get-method-restrictions rab 1)
(list-defclasses)
(get-defclass-list)
(describe-class woz)
(class-slots woz)
(class-slots woz inherit)
(class-abstractp woz)
(class-superclasses woz)
(class-superclasses woz inherit)
(class-subclasses foo)
(class-subclasses foo inherit)
(slot-facets woz x)
(slot-sources woz x)
(list-defmessage-handlers)
(get-defmessage-handler-list)
(list-defmessage-handlers woz)
(get-defmessage-handler-list woz)
(list-defmessage-handlers woz inherit)
(get-defmessage-handler-list woz inherit)
(list-definstances)
(get-definstances-list)
(get-defrule-list abc)
(get-defmessage-handler-list no-exist)
(get-defmethod-list no-exist)
(get-defmessage-handler-list USER junk)
(get-defmessage-handler-list USER inherit abc)
(get-defmethod-list oof abc)
