(superclassp)
(superclassp BOGUS)
(superclassp USER)
(superclassp USER BOGUS)
(superclassp USER OBJECT)
(superclassp OBJECT USER)
(superclassp 1 2 3)
(subclassp)
(subclassp BOGUS)
(subclassp USER)
(subclassp USER BOGUS)
(subclassp USER OBJECT)
(subclassp OBJECT USER)
(subclassp 1 2 3)
(slot-existp)
(slot-existp BOGUS)
(slot-existp BOGUS bogus)
(slot-existp USER bogus)
(slot-existp TEST bogus)
(slot-existp TEST x)
(slot-existp SUBTEST x)
(slot-existp 1 2 3)
(message-handler-existp)
(message-handler-existp BOGUS)
(message-handler-existp BOGUS bogus)
(message-handler-existp BOGUS bogus bogus)
(message-handler-existp USER init)
(message-handler-existp USER init primary)
(message-handler-existp USER init around)
(message-handler-existp USER init after)
(message-handler-existp USER init before)
(message-handler-existp A delete primary)
(message-handler-existp TEST get-x)
(message-handler-existp TEST put-x)
(next-handlerp)
(call-next-handler)
(override-next-handler 1 2 3)
(make-instance a1 of A1 (x 0))
(send [a1] print-args 1 2 3 4)
(make-instance [a2] of A2)
(send [a2] print-args 1 2 3 4)
(init-slots)
(make-instance [mea] of MY-EXTERNAL-ADDRESS (blah 0))
(send [mea] put-blah 12a5H)
(send [mea] get-blah)
(watch instances)
(unmake-instance mea)
(unmake-instance *)
(unmake-instance)
(make-instance * of A1 (x 0))
(make-instance a2 of A2)
(unmake-instance *)
(unmake-instance *)
(unwatch instances)
(make-instance a1 of A1 (x 0))
(class)
(class a1)
(class [a1])
(class (sym-cat [ a1 ]))
(class (symbol-to-instance-name (sym-cat a "1")))
(class 34)
(instance-name)
(instance-address)
(instance-address a1)
(instance-address [a1])
(instance-name (instance-address a1))
(instance-name bogus)
(instance-address bogus)
(symbol-to-instance-name)
(symbol-to-instance-name bogus)
(symbol-to-instance-name [bogus])
(symbol-to-instance-name 42)
(instance-name-to-symbol)
(instance-name-to-symbol [bogus])
(instance-name-to-symbol bogus)
(instance-name-to-symbol 42)
(instancep)
(instancep 42)
(instancep (instance-address [a1]))
(instancep a1)
(instancep [junk])
(instance-namep (instance-address [a1]))
(instance-addressp (instance-address [a1]))
(instance-namep [a1])
(instance-addressp [a1])
(instance-namep bogus)
(instance-addressp bogus)
(instance-namep)
(instance-addressp)
(instance-existp)
(instance-existp a1)
(instance-existp [a1])
(instance-existp [junk])
(instance-existp (instance-address a1))
(bind ?*x* (instance-address [a1]))
(unmake-instance *)
(instance-addressp ?*x*)
(instance-name ?*x*)
(send ?*x* print)
(make-instance b1 of B1 (x 0))
(slot-existp)
(slot-existp (class [b1]))
(slot-existp (class [b1]) x inherit)
(slot-existp (class [b1]) y inherit)
(slot-existp bogus x inherit)
(slot-existp (class [b1]) bogus inherit)
(slot-writablep (class [b1]) x)
(slot-writablep (class [b1]) y)
(slot-initablep (class [b1]) x)
(slot-initablep (class [b1]) y)
(slot-writablep)
(slot-writablep (class [b1]))
(slot-writablep (class [b1]) bogus)
(slot-writablep bogus x)
(slot-initablep)
(slot-initablep (class [b1]))
(slot-initablep (class [b1]) bogus)
(slot-writablep bogus x)
(get x)
(put x)
(make-instance [junk] of JUNK (x 0) (y 0))
(send [junk] my-put x a b c d e)
(send [junk] my-get x)
(send [junk] my-get y)
(mv-slot-replace junk x 2 4 2 3 4)
(send [junk] get-x)
(mv-slot-insert junk x 2 4 2 3 4)
(send [junk] get-x)
(mv-slot-delete junk x 2 4)
(send [junk] get-x)
(send [junk] put-x a b c d e)
(send [junk] my-replace x 2 4 2 3 4)
(send [junk] get-x)
(send [junk] my-insert x 2 4 2 3 4)
(send [junk] get-x)
(send [junk] my-delete x 2 4)
(send [junk] get-x)
(send [junk] put-x)
(mv-slot-insert junk x 1 abc)
(mv-slot-insert)
(mv-slot-delete)
(mv-slot-replace)
(mv-slot-replace bogus x 1 2 abc)
(mv-slot-replace junk bogus 1 2 abc)
(mv-slot-replace junk x 1 100 abc)
(send [junk] my-replace x 1 100 abc)
(mv-slot-replace junk y 1 2 def)
(class-existp)
(class-existp 34)
(class-existp abc def)
(class-existp USER)
(class-existp user)
(class-abstractp)
(class-abstractp 1)
(class-abstractp USER 1)
(class-abstractp USER)
(class-abstractp TEST)
(class-superclasses)
(class-superclasses 1)
(class-superclasses WOZBANG)
(class-superclasses WOZBANG 1)
(class-superclasses WOZBANG junk)
(class-superclasses WOZBANG inherit)
(class-subclasses)
(class-subclasses 1)
(class-subclasses NUMBER)
(class-subclasses NUMBER 1)
(class-subclasses NUMBER junk)
(class-subclasses NUMBER inherit)
(class-subclasses OBJECT inherit)
(get-defmessage-handler-list)
(get-defmessage-handler-list 1)
(get-defmessage-handler-list JUNK)
(get-defmessage-handler-list JUNK 1)
(get-defmessage-handler-list JUNK junk)
(get-defmessage-handler-list JUNK inherit)
(slot-facets)
(slot-facets 1)
(slot-facets bad-class foo)
(slot-facets TEST 1)
(slot-facets TEST ziggy)
(slot-facets TEST x)
(slot-facets SUBTEST x)
(slot-sources)
(slot-sources 1)
(slot-sources bad-class foo)
(slot-sources TEST 1)
(slot-sources TEST ziggy)
(slot-sources TEST x)
(slot-sources SUBTEST x)
(slot-sources DOOGLE z)
