(clear)
(deftemplate foo (field x) (multifield y))
(deffacts d1)
(deffacts d2 (a))
(deffacts d3 (a) (b) (c))
(deffacts d4 (foo (x 3) (y)))
(deffacts d5 (a) (foo (y a) (x 3)))
(deffacts d6 (foo (y a b)) (b) (foo (x 3)) (d))
(deffacts *)
(list-deffacts d6)
(list-deffacts)
(ppdeffacts d1)
(ppdeffacts d2)
(ppdeffacts d3)
(ppdeffacts d4)
(ppdeffacts d5)
(ppdeffacts d6)
(undeffacts)
(undeffacts 10)
(undeffacts bad-name)
(undeffacts d6 10)
(list-deffacts)
(undeffacts d1)
(undeffacts d2)
(undeffacts d3)
(list-deffacts)
(undeffacts *)
(list-deffacts)
(undeffacts *)
(list-deffacts)
(clear) ; Some new 6.0 features
(deffacts BOGUS::d5)
(defmodule FOO)
(deffacts FOO::d1)
(deffacts FOO::d2)
(defmodule BAR)
(deffacts BAR::d2)
(deffacts BAR::d3)
(list-deffacts BOGUS)
(list-deffacts FOO 7)
(list-deffacts FOO)
(list-deffacts BAR)
(list-deffacts)
(list-deffacts *)
(get-deffacts-list 7)
(get-deffacts-list BOGUS 7)
(get-deffacts-list)
(get-deffacts-list BOGUS)
(get-deffacts-list FOO)
(get-deffacts-list BAR)
(get-deffacts-list *)
(ppdeffacts d1)
(ppdeffacts d2)
(ppdeffacts d3)
(ppdeffacts BOGUS::d2)
(ppdeffacts FOO::d1)
(ppdeffacts FOO::d2)
(ppdeffacts FOO::d3)
(ppdeffacts BAR::d1)
(ppdeffacts BAR::d2)
(ppdeffacts BAR::d3)
(deffacts-module)
(deffacts-module bogus)
(deffacts-module d3 7)
(deffacts-module d2)
(deffacts-module d3)
(deffacts-module FOO::d1)
(deffacts-module FOO::d2)
(deffacts-module BAR::d2)
(deffacts-module BAR::d3)
(undeffacts BOGUS::d2)
(undeffacts FOO::d2)
(list-deffacts *)
(undeffacts BAR::d2)
(list-deffacts *)
(undeffacts *)
(list-deffacts *)
