(clear)
(defglobal ?*d1* = 1)
(defglobal ?*d2* = 2)
(defglobal ?*d3* = 3)
(defglobal ?*d4* = 4)
(defglobal ?*d5* = 5)
(defglobal ?*d6* = 6)
(defglobal ?*** = 7)
(list-defglobals d6)
(list-defglobals)
(ppdefglobal d1)
(ppdefglobal d2)
(ppdefglobal d3)
(ppdefglobal d4)
(ppdefglobal d5)
(ppdefglobal d6)
(undefglobal)
(undefglobal 10)
(undefglobal bad-name)
(undefglobal d6 10)
(list-defglobals)
(undefglobal d1)
(undefglobal d2)
(undefglobal d3)
(list-defglobals)
(undefglobal *)
(list-defglobals)
(undefglobal *)
(list-defglobals)
(clear)
(defglobal ?*x* = 3 ?*y* = ?*x* ?*z* = (+ 4 ?*x*))
(defglobal ?*q* = (create$ a b c))
(reset)
(show-defglobals x y)
(show-defglobals)
(ppdefglobal x)
(ppdefglobal y)
(ppdefglobal z)
(ppdefglobal q)
(get-reset-globals)
(get-reset-globals TRUE)
(set-reset-globals)
(set-reset-globals TRUE FALSE)
(set-reset-globals 10)
(get-reset-globals)
(set-reset-globals FALSE)
(get-reset-globals)
(bind ?*x* a)
(bind ?*y* 3.2)
(bind ?*z* [x])
(bind ?*q* "red")
(reset)
(show-defglobals)
(set-reset-globals TRUE)
(get-reset-globals)
(reset)
(show-defglobals)
(clear)
(show-defglobals)
(ppdefglobal x)
(clear) ; Some new 6.0 features
(defglobal BOGUS d5 = 5)
(defmodule FOO)
(defglobal FOO ?*d1* = 1)
(defglobal FOO ?*d2* = 2)
(defmodule BAR)
(defglobal BAR ?*d2* = 2)
(defglobal BAR ?*d3* = 3)
(list-defglobals BOGUS)
(list-defglobals FOO 7)
(list-defglobals FOO)
(list-defglobals BAR)
(list-defglobals)
(list-defglobals *)
(get-defglobal-list 7)
(get-defglobal-list BOGUS 7)
(get-defglobal-list)
(get-defglobal-list BOGUS)
(get-defglobal-list FOO)
(get-defglobal-list BAR)
(get-defglobal-list *)
(ppdefglobal d1)
(ppdefglobal d2)
(ppdefglobal d3)
(ppdefglobal BOGUS::d2)
(ppdefglobal FOO::d1)
(ppdefglobal FOO::d2)
(ppdefglobal FOO::d3)
(ppdefglobal BAR::d1)
(ppdefglobal BAR::d2)
(ppdefglobal BAR::d3)
(defglobal-module)
(defglobal-module bogus)
(defglobal-module d3 7)
(defglobal-module d2)
(defglobal-module d3)
(defglobal-module FOO::d1)
(defglobal-module FOO::d2)
(defglobal-module BAR::d2)
(defglobal-module BAR::d3)
(show-defglobals)
(show-defglobals 7)
(show-defglobals BOGUS)
(show-defglobals FOO 7)
(show-defglobals FOO)
(show-defglobals BAR)
(show-defglobals *)
(undefglobal BOGUS::d2)
(undefglobal FOO::d2)
(list-defglobals *)
(undefglobal BAR::d2)
(list-defglobals *)
(undefglobal *)
(list-defglobals *)
