(unwatch all)
(clear)
(dribble-on "Actual//dfnxexe.out")
(batch "dfnxexe.bat")
(dribble-off)
(clear)
(open "Results//dfnxexe.rsl" dfnxexe "w")
(load "compline.clp")
(printout dfnxexe "dfnxexe.bat differences are as follows:" crlf)
(compare-files "Expected//dfnxexe.out" "Actual//dfnxexe.out" dfnxexe)
(close dfnxexe)
