(unwatch all)
(clear)
(conserve-mem off)
(dribble-on "Actual//dfnxcmd.out")
(batch "dfnxcmd.bat")
(dribble-off)
(clear)
(open "Results//dfnxcmd.rsl" dfnxcmd "w")
(load "compline.clp")
(printout dfnxcmd "dfnxcmd.bat differences are as follows:" crlf)
(compare-files "Expected//dfnxcmd.out" "Actual//dfnxcmd.out" dfnxcmd)
(close dfnxcmd)
