(unwatch all)
(clear)
(setgen 1)
(dribble-on "Actual//dftmpfun.out")
(batch "dftmpfun.bat")
(dribble-off)
(clear)
(open "Results//dftmpfun.rsl" dftmpfun "w")
(load "compline.clp")
(printout dftmpfun "dftmpfun.bat differences are as follows:" crlf)
(compare-files "Expected//dftmpfun.out" "Actual//dftmpfun.out" dftmpfun)
(close dftmpfun)
