(unwatch all)
(clear)
(dribble-on "Actual//dftmpcmd.out")
(batch "dftmpcmd.bat")
(dribble-off)
(clear)
(open "Results//dftmpcmd.rsl" dftmpcmd "w")
(load "compline.clp")
(printout dftmpcmd "dftmpcmd.bat differences are as follows:" crlf)
(compare-files "Expected//dftmpcmd.out" "Actual//dftmpcmd.out" dftmpcmd)
(close dftmpcmd)
