(unwatch all)
(clear)
(set-dynamic-constraint-checking TRUE)
(dribble-on "Actual//dyobjcst.out")
(batch "dyobjcst.bat")
(dribble-off)
(set-dynamic-constraint-checking FALSE)
(clear)
(open "Results//dyobjcst.rsl" dyobjcst "w")
(load "compline.clp")
(printout dyobjcst "dyobjcst.bat differences are as follows:" crlf)
(compare-files "Expected//dyobjcst.out" "Actual//dyobjcst.out" dyobjcst)
(close dyobjcst)
