(unwatch all)
(clear)
(dribble-on "Actual//factsav.out")
(batch "factsav.bat")
(dribble-off)
(clear)
(open "Results//factsav.rsl" factsav "w")
(load "compline.clp")
(printout factsav "factsav.bat differences are as follows:" crlf)
(compare-files "Expected//factsav.out" "Actual//factsav.out" factsav)
(close factsav)
