(clear)
(get-focus 6)
(get-focus-stack 6)
(pop-focus 6)
(list-focus-stack 6)
(clear-focus-stack 6)
(clear)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(clear-focus-stack)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(reset)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(defmodule A)
(defmodule B)
(focus A B)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(pop-focus)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(pop-focus)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(pop-focus)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(clear-focus-stack)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(focus A B)
(clear-focus-stack)
(get-focus)
(get-focus-stack)
(list-focus-stack)
(focus 6)
(focus "A")
(focus A 6)
(focus C)
(focus)
(list-focus-stack)
(focus A)
(focus B)
(list-focus-stack)
(focus A B)
(list-focus-stack)
(clear)
(defmodule A)
(defmodule B)
(watch focus 6)
(unwatch focus 6)
(focus A B)
(focus B C)
(list-focus-stack)
(clear-focus-stack)
(watch focus)
(reset)
(focus A B)
(pop-focus)
(clear-focus-stack)
(focus A B)
(clear)
(run)
(run)
(defmodule A)
(defmodule B)
(focus A B)
(run)
(unwatch focus)
(reset)
(focus A B)
(clear)
