(unwatch all)
(clear)
(dribble-on "Actual//gnrcerr.out")
(batch "gnrcerr.bat")
(dribble-off)
(clear)
(open "Results//gnrcerr.rsl" gnrcerr "w")
(load "compline.clp")
(printout gnrcerr "gnrcerr.bat differences are as follows:" crlf)
(compare-files "Expected//gnrcerr.out" "Actual//gnrcerr.out" gnrcerr)
(close gnrcerr)
