(unwatch all)
(clear)
(progn
  (bind ?old (set-sequence-operator-recognition TRUE))
  (load "gnrcexe.clp")
  (set-sequence-operator-recognition ?old))
(dribble-on "Actual//gnrcexe.out")
(testit)
(dribble-off)
(clear)
(open "Results//gnrcexe.rsl" gnrcexe "w")
(load "compline.clp")
(printout gnrcexe "gnrcexe.clp differences are as follows:" crlf)
(compare-files "Expected//gnrcexe.out" "Actual//gnrcexe.out" gnrcexe)
(close gnrcexe)
