(unwatch all)
(clear)
(setgen 1)
(dribble-on "Actual//insmodul.out")
(batch "insmodul.bat")
(dribble-off)
(clear)
(open "Results//insmodul.rsl" insmodul "w")
(load "compline.clp")
(printout insmodul "insmodul.clp differences are as follows:" crlf)
(compare-files "Expected//insmodul.out" "Actual//insmodul.out" insmodul)
(close insmodul)
