(unwatch all)
(clear)
(load insquery.clp)
(dribble-on "Actual//insquery.out")
(batch "insquery.bat")
(dribble-off)
(clear)
(open "Results//insquery.rsl" insquery "w")
(load "compline.clp")
(printout insquery "insquery.clp differences are as follows:" crlf)
(compare-files "Expected//insquery.out" "Actual//insquery.out" insquery)
(close insquery)
