(clear)
(mem-used 10)
(progn (mem-used) TRUE)
(mem-requests 20)
(progn (mem-requests) TRUE)
(release-mem 10)
(progn (release-mem) TRUE)
(conserve-mem)
(conserve-mem on off)
(conserve-mem off)
(defrule foo =>)
(deftemplate foo)
(deffacts foo)
(defglobal ?*foo* = foo)
(deffunction foo ())
(defgeneric bar)
(defmethod bar ())
(defclass SNAFU (is-a USER) (role concrete))
(definstances foo (x of SNAFU))
(defmessage-handler SNAFU fubar ())
(ppdefrule foo)
(ppdeftemplate foo)
(ppdefglobal foo)
(ppdeffunction foo)
(ppdefgeneric bar)
(ppdefmethod bar 1)
(ppdefclass SNAFU)
(ppdefinstances foo)
(ppdefmessage-handler SNAFU fubar)
(conserve-mem on)
(defrule foo =>)
(deftemplate foo)
(deffacts foo)
(defglobal ?*foo* = foo)
(deffunction foo ())
(defgeneric bar)
(defmethod bar ())
(undefinstances foo)
(defclass SNAFU (is-a USER) (role concrete))
(definstances foo (x of SNAFU))
(defmessage-handler SNAFU fubar ())
(ppdefrule foo)
(ppdeftemplate foo)
(ppdefglobal foo)
(ppdeffunction foo)
(ppdefgeneric bar)
(ppdefmethod bar 1)
(ppdefclass SNAFU)
(ppdefinstances foo)
(ppdefmessage-handler SNAFU fubar)
(conserve-mem off)
