(unwatch all)
(clear)
(dribble-on "Actual//modulprt.out")
(batch "modulprt.bat")
(dribble-off)
(clear)
(open "Results//modulprt.rsl" modulprt "w")
(load "compline.clp")
(printout modulprt "modulprt.bat differences are as follows:" crlf)
(compare-files "Expected//modulprt.out" "Actual//modulprt.out" modulprt)
(close modulprt)
