(unwatch all)
(clear)
(load "multinh.clp")
(dribble-on "Actual//multinh.out")
(testit)
(dribble-off)
(clear)
(open "Results//multinh.rsl" multinh "w")
(load "compline.clp")
(printout multinh "multinh.clp differences are as follows:" crlf)
(compare-files "Expected//multinh.out" "Actual//multinh.out" multinh)
(close multinh)
