(unwatch all)
(clear)
(dribble-on "Actual//tmplmslt.out")
(batch "tmplmslt.bat")
(dribble-off)
(clear)
(open "Results//tmplmslt.rsl" tmplmslt "w")
(load "compline.clp")
(printout tmplmslt "tmplmslt.bat differences are as follows:" crlf)
(compare-files "Expected//tmplmslt.out" "Actual//tmplmslt.out" tmplmslt)
(close tmplmslt)
