(clear)                          
(sort)
(sort 8)
(sort 8.1)
(sort a)
(sort "a")
(sort [a])
(sort >)
(sort > 3 2 5 1 2)
(sort agenda 3 2 5 1 2)

(deffunction str> (?a ?b)
   (> (str-compare ?a ?b) 0))
(sort str> ax aa dj ce bx)

(deffunction three (?a ?b ?c)
   (> ?a ?b ?c))
(sort three 4 8 2 5 3)
(clear)
(get-class-defaults-mode)
(get-class-defaults-mode 10)
(set-class-defaults-mode)
(set-class-defaults-mode 10)
(set-class-defaults-mode symbol)
(set-class-defaults-mode conservation x)
(defclass A (is-a USER) (slot x))
(describe-class A)
(set-class-defaults-mode conservation)
(get-class-defaults-mode)
(defclass B (is-a USER) (slot x))
(describe-class B)
(set-class-defaults-mode convenience)
(get-class-defaults-mode)
